### ISSUE TITLE
panic in NewKnowledgeBaseInstance if rule description is missing

### ISSUE THREAD

**Issue by k2s** [hyperjumptech/grule-rule-engine#120]
**Describe the bug**
If at least 1 rule doesn't contain description call to `NewKnowledgeBaseInstance()` will panic.

**To Reproduce**
1. Add rule to GRL file

```
rule WillPanic {
    when Num == 1
    then
        Num = 2;
        Log("this should be logged");
}
```

2. load it with `NewFileResource()`
3. execute `lib.NewKnowledgeBaseInstance(kbName, kbVersion)`
4. app will crash

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xcec79c]
```

**Expected behavior**
Maybe description should be optional. Grule should print clear error message including the problematic rule name.

**Comment by newm4n** [comment]
Well, description is very  helpful, and even more important when you have long rule body or many-many rule.
Not mandating rule description is easily be done but to add a simple description also so easy to do.
I would like to see some vote to convince me to make rule description optional.

I will keep this issue open until I see more reactions. If none, I will close this issue in a month or two.

**Comment by k2s** [comment]
* I don't vote for optional :-), I am totally fine to write description
* but it would be helpful if grule doesn't crash, but prints the rule name or GRL file name + line if I forgot it

thank you

thank you

**Comment by niallnsec** [comment]
I have the same thoughts as @k2s 

I think enforcing the description encourages better quality rules but it would be good to avoid panics which could potentially kill a larger application.

**Comment by newm4n** [comment]
Its close to a month. 
I've made a pull request #126  for this.
No more panic when you call `NewKnowledgeBaseInstance` if any of the rule have no Description, a default description is assigned to those rules.
