### ISSUE TITLE
Integer overflow when building for ARM7

### ISSUE THREAD

**Issue by twystd** [hyperjumptech/grule-rule-engine#133]
Building a target for ARM7 (`go build env GOOS=linux   GOARCH=arm GOARM=7 ...`) with a project that depends on `grule-rule-engine` v1.6.2 fails with the following error:

```
env GOOS=linux   GOARCH=arm GOARM=7 go build -o dist/development/arm7    ./...
# github.com/hyperjumptech/grule-rule-engine/antlr/parser/grulev2
../../../go/pkg/mod/github.com/hyperjumptech/grule-rule-engine@v1.6.2/antlr/parser/grulev2/grulev2_parser.go:1255: constant 4026532015 overflows int
../../../go/pkg/mod/github.com/hyperjumptech/grule-rule-engine@v1.6.2/antlr/parser/grulev2/grulev2_parser.go:2835: constant 4034920623 overflows int
```

**Comment by niallnsec** [comment]
This seems to be related to https://github.com/antlr/antlr4/issues/2433

**Comment by newm4n** [comment]
@niallnsec So we have to do this every time antler4 done generating parsers ?
Can we automate this some how ? Any Ideas ?

**Comment by niallnsec** [comment]
Yeah we would have to apply the patch every time the parsers are regenerated. I think we could automate the process with a go generate tag though.
I'll see if I can make it work and update later on.

**Comment by twystd** [comment]
Confirmed that I can now build for ARM7 - thanks for the quick turnaround!
