### ISSUE TITLE
benchmark params error

### ISSUE THREAD

**Issue by hongyuefan** [hyperjumptech/grule-rule-engine#137]
in LoadRules_benchmark_test.go file, i find in code file the .grl file name is "100_complicated_rules.grl", but in folder the file name is "100_rules.grl". so the benchmark data is not right.

**Comment by jinagamvasubabu** [comment]
Hi @hongyuefan , you are right. my bad recent file name changes did that. will fix that re run that tests and raise a separate PR for the same

**Comment by hongyuefan** [comment]
> Hi @hongyuefan , you are right. my bad recent file name changes did that. will fix that re run that tests and raise a separate PR for the same

from the official data "To load 100 rules into knowledgeBase it took 17523 ns/op".

in fact, to load "100_rules.grl" it took 110922360 ns/op.   

so its difficult to use。。😭

**Comment by jinagamvasubabu** [comment]
Hi @hongyuefan , i have updated the benchmark results, PR for that - https://github.com/hyperjumptech/grule-rule-engine/pull/138/files

Coming to your question i ran benchmark for 10 times with different N values 

## Load 100 and 1000 rules:
benchmarks for Loading 100 and 1000 rules are `22628754 ns/op` (`22.628754ms`) and `261857403 ns/op` (`~261ms`) . Yes i see there is a room for improvement, but the results are in NS (nano seconds) 

Loading rules into knowledgeBase should be onetime and its a costly operation to do and you should do it only when you are adding a new rule/ editing an existing rule. 

## Executing fact against 100 and 1000 rules:
benchmarks for Executing a fact against 100 and 1000 rules are `~35847 ns/op`  (`~0.035847ms`) and `~475685 ns/op`(`~0.475685ms`) and i think this is fine
