### ISSUE TITLE
Support to jump to other rule

### ISSUE THREAD

**Issue by amyd99** [hyperjumptech/grule-rule-engine#140]
**Is your feature request related to a problem? Please describe.**
It's not very convenient to handle some sort of decision problem, like:

```
Condition A --y--> Rule A
           \--n--> Rule B --y--> Rule C
                          \--n--> Rule D
```

**Describe the solution you'd like**
Add a built-in function like Jump(ruleName). It is used in Then clause to jump to other rule.

**Comment by newm4n** [comment]
A rule is always comprise of "when" and "then", 
And all when is always evaluated in every cycle to choose which candidate to be executed.
This "Jump" function is not allowing all rule when to be executed.
What if on the target rule to-jump, the when condition is not met ?

You could simply use a fact object to do this though...

```go
type Stage struct {
     StageName string
}
```

And your Rules be like :

```
rule StageAConditionX {
    when Stage.StageName=="StageA" and SomeFact.ConditionX
    then 
          // do something here ...
           Stage.StageName="StageB";
}

rule StageAConditionY {
    when Stage.StageName=="StageA" and SomeFact.ConditionY
    then 
          // do something here ...
           Stage.StageName="StageC";
}

rule StageBConditionR {
    when Stage.StageName=="StageB" and SomeFact.ConditionX
    then 
          // do something here ...
           Stage.StageName="StageD";
}

rule StageBConditionS {
    when Stage.StageName=="StageB" and SomeFact.ConditionY
    then 
          // do something here ...
           Stage.StageName="StageF";
}

// so on an on
```

**Comment by amyd99** [comment]
Understood. Thanks a lot. @newm4n

**Comment by newm4n** [comment]
@amyd99  thanks a lot for trying grule. Truly appreciated it.  You can close this issue when you're done.
