### ISSUE TITLE
Can't do function chain in "then" statement

### ISSUE THREAD

**Issue by TeCHiScy** [hyperjumptech/grule-rule-engine#142]
**Describe the bug**
Can't do function chain in "then" statement as described in http://hyperjumptech.viewdocs.io/grule-rule-engine/GRL_en/

    when
        Fact.Function().StringField == "" ||
        Fact.Function("contant").ObjField.OtherFunction() &&
        ...
    then
        Fact.CallFunction().CallAnotherFunction();
        ...

**To Reproduce**
This is the test code:

	rule := `rule test "test" {
		when
		  true
		then
		  A.Get().Set();
	  }`

	lib := ast.NewKnowledgeLibrary()
	rb := builder.NewRuleBuilder(lib)
	err := rb.BuildRuleFromResource("test", "0.0.1", pkg.NewBytesResource([]byte(rule)))
	fmt.Printf("%v", err)

I got this error:
line 5:11 mismatched input '.' expecting ';'
ERRO[0000] GRL error, after '[A . Get ( )]' and then unexpected '.'  lib=grule struct=GruleParserV3Listener
ERRO[0000] Loading rule resource : Byte array resources 65 bytes failed. Got GRL error, after '[A . Get ( )]' and then unexpected '.'. Time take 2 ms  lib=grule-rule-engine package=builder
error were found before builder bailing out. Got GRL error, after '[A . Get ( )]' and then unexpected '.'

which indicates the rule can not successfully be compiled

**Expected behavior**
The rule showed above runs with no error.

**Additional context**
None

**Comment by newm4n** [comment]
The latest version patch v1.7.1 fixes this issue.
