### ISSUE TITLE
JSON fact supported?

### ISSUE THREAD

**Issue by ddebrunner** [hyperjumptech/grule-rule-engine#144]
Are JSON facts supported as described in issue #98?

The comments say "3. JSON Fact Support " will be part of the update and says it's released in 1.6.0 but I'm not seeing any tests, example for it (or maps).

Any pointers to how to use it if it is supported?

**Comment by newm4n** [comment]
Yeah, its been in my pipeliine for couple of weeks now. Some of the code already there. I just need to try to push it again.

**Comment by newm4n** [comment]
I've made PR ( #148 ) for this. Finally. Need some documentation to help people know how to use this.
I wont release this until sufficient documentation is there. so Please try go get using last commit .
`go get github.com/hyperjumptech/grule-rule-engine@504be7412dc4d67c30473fb225d4549922fafe54` at least until it released.
Sample codes that uses JSON in data context can be seen in `examples/JSONDataContext_test.go`

**Comment by newm4n** [comment]
I know, its been only 19 hours. But I can't sleep. So I created some documentation about it and release it. [v1.8.0](https://github.com/hyperjumptech/grule-rule-engine/releases/tag/v1.8.0) . 

Happy testing, all bugs or features request appreciated !!!
