### ISSUE TITLE
When an negated expression is nested in another expression, the knowledgeLibrary.NewKnowledgeBaseInstance() method throws panic error randomly in version 1.7.1.

### ISSUE THREAD

**Issue by xiaohouzikeke** [hyperjumptech/grule-rule-engine#146]
**Describe the bug**
When an negated expression is nested in another expression, the knowledgeLibrary.NewKnowledgeBaseInstance() method throws panic error randomly in version 1.7.1.

**To Reproduce**
1. I have 2 rules like these:
rule Rule1 "simple rule" {
    when
        !(!false)
    then
        Retract("Rule1");
}

rule Rule2 "complex rule" {
    when
        !((!false) && true)
    then
        Retract("Rule2");
}
2. When I run these two rules, I got program panic error randomly.  
3. The panic error outputs(grule-rule-engine/ast/RuleEntry.go):
panic: RuleEntry clone failed : 
original [R(N:Rule1 DEC:"simple rule" SAL:0 W:WS(E(SE(!E(EA(A(!A(C(bool->false)))))))) T:TS(TEL(TE(A(F(n:Retract,AL(E(EA(A(C(string->"Rule1"))))))))))})] 
clone    [R(N:Rule1 DEC:"simple rule" SAL:0 W:WS(E(SE(E(EA(A(!A(C(bool->false)))))))) T:TS(TEL(TE(A(F(n:Retract,AL(E(EA(A(C(string->"Rule1"))))))))))})]

**Expected behavior**
Nested negated expression should be cloned correctly.

**Additional context**
When I trace the code, I doubt if Expression.go 100 Line have a bug. I add "clone.Negated = e.Negated" after 100 line, it works.
So, Please check if it is a bug to be fixed. Thanks!

**Comment by newm4n** [comment]
I made a PR #147 that fix this issue.

**Comment by newm4n** [comment]
@xiaohouzikeke  your suspicion is correct. its fixed on path v1.7.2

**Comment by xiaohouzikeke** [comment]
@newm4n Thanks! Waiting for v1.7.2

**Comment by newm4n** [comment]
@xiaohouzikeke  is already there mate ;)

**Comment by xiaohouzikeke** [comment]
@newm4n Yeah, It works.
