### ISSUE TITLE
fatal error: concurrent map iteration while resetting the working memory

### ISSUE THREAD

**Issue by jinagamvasubabu** [hyperjumptech/grule-rule-engine#150]
**Describe the bug**
Today i have seen one issue `fatal error: concurrent map iteration`  while executing the fact against rules and when i check the logs in kibana what i found is

It happened while executing the rules in a realtime concurrent scenario

**To Reproduce**
Not sure how to reproduce this because this happens in realtime when there are lot of concurrent requests.

**Identified place**:
 ```go
// ResetAll sets all expression evaluated status to false.
// Returns true if any expression was reset, false if otherwise
func (e *WorkingMemory) ResetAll() bool {
	reseted := false
	for _, expr := range e.expressionSnapshotMap {
		expr.Evaluated = false
		reseted = true
	}
	for _, expr := range e.expressionAtomSnapshotMap { -- this line
		expr.Evaluated = false
		reseted = true
	}
	return reseted
}
```

**Expected behavior**
We should not see the mentioned error

**Suggested solution**
```go
Can we keep mutex lock ?
func (e *WorkingMemory) ResetAll() bool {
	reseted := false
        syncD.Lock()
	defer syncD.Unlock()
	for _, expr := range e.expressionSnapshotMap {
		expr.Evaluated = false
		reseted = true
	}
	for _, expr := range e.expressionAtomSnapshotMap { -- this line
		expr.Evaluated = false
		reseted = true
	}
	return reseted
}
```
**Additional context**

**Comment by jinagamvasubabu** [comment]
but adding a mutex will increase the latency, i ran benchmark with adding a mutex lock for executing fact. Closing this issue not sure what to do here

**Comment by newm4n** [comment]
The `WorkingMemory` is cloned along with the `Knoledgebase`. When you call `lib.NewKnowledgeBaseInstance()`, the built `Knowledgebase` inside `KnowledgeLibrary` get cloned. Thus, `Knowledgebase` execution inside the engine is local to that engine. 

So, when your server start, you should build all your rules GRL using the builder into `Knowledgelibrary` as in 

```go
lib := ast.NewKnowledgeLibrary()
rb := builder.NewRuleBuilder(lib)
err = rb.BuildRuleFromResource("KB", "0.0.1", pkg.NewBytesResource([]byte(...)))
```

For **EVERY** incoming request, when you want to execute some rule toward request data,
you create `DataContext` (and get your facts into it),  get instance of the `Knowledgebase` from the library, create new engine, and execute the engine using `DataContext` and the new instance of `Knowledgebase`.

```go
// In every request.
// Create DataContext to hold Facts.
dataContext := ast.NewDataContext()
dataContext.Add("F", Obj)

// New engine
eng1 := &engine.GruleEngine{MaxCycle: 5}

// Get knowledgebase instance which return the clone (including WorkingMemory clone)
kb := lib.NewKnowledgeBaseInstance("Test108", "0.0.1")

// Execute the engine using the DataContext and cloned Knowledgebase instance.
err = eng1.Execute(dataContext, kb)
```

I hope this solve your concurrency issue.
Please do tell me if this still happening under heavy concurrent request.
I might have to switch to `sync.Map`. Or make it as a configuration flag to enable mutex when executing engine, to give option for the user whether they want to go "Stability" over "Speed"

**Comment by jinagamvasubabu** [comment]
Actually i am doing the same you mentioned except the one, which is using `KnowledgeBase.GetKnowledgeBase` instead of getting a new instance `KnowledgeBase.NewKnowledgeBaseInstance` and the reason i thought it was a costly operation (correct me if i am wrong)

coming to solution proposed, i will do the changes and let you know if i face this issue again. may be this would take some :)

**Comment by jinagamvasubabu** [comment]
Hi @newm4n , I have changed my strategy of building the knowledgeBase everytime before executing the fact to build only once (knowledgeBase) and keep it in memory and pass it to executeFact everytime. Looks like this solved the issue.

I think this is fine for now, we will close the issue. let me know if you have any concerns
