### ISSUE TITLE
Is there an efficient way to call math functions in then statement? 

### ISSUE THREAD

**Issue by TeCHiScy** [hyperjumptech/grule-rule-engine#158]
**Is your feature request related to a problem? Please describe.**
I'd like to design a promotion module, which takes a cart and outputs the promoted cart.
In my rule, sometime I need to call math functions like math.Floor, math.Ceil, math.Abs, math.Min, math.Max to handle the price, the discount, etc..
But I found it's difficult to do so in the rule engine.

**Describe the solution you'd like**
Put some common used math funtions (or maybe the whole math lib?) into the engine as built-in functions, so that I can call them directly in the rule.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by newm4n** [comment]
@TeCHiScy thanks a lot for pointing this out to me.
Basically, as the Tutorials Point explained "A Rule Engine allows you to define **What to Do** and not **How to do it**.” means that, the engine will give you a clue (some value sets by the rules) and after the engine is finished execution, you took these value for further processing. Its not the job of the engine to do "real" calculation such as discounts, prices etc. Lets see how Grule approach this ...

In grule "What to Do" is emphasized by the engine to invoke your function while the "How to do it" part is your function body. Thus your `Fact` should contains these function to calculate discounts, prices, etc. As you know exactly how to calculate them, you should define the function (in you facts) and let the rule call them (from the GRL). However ...

To have some very basic math function would be beneficial. Something like

A constants function...

```go
123.456.round()
fact.FloatVal.round()
```

or a built in function ...

```go
Round(123.456)
Round(fact.FloatVal)
```

I will mark this as an improvement.

**Comment by TeCHiScy** [comment]
Yeah, having round/ceil/floor may help handling the conversion from float64 to int64 as well. Thanks in advance, for the enhancement.

**Comment by TeCHiScy** [comment]
Great job! I'll try the new version asap
