### ISSUE TITLE
Documentation updates

### ISSUE THREAD

**Issue by derekwyatt** [hyperjumptech/grule-rule-engine#160]
**Describe the bug**
No bug. I'm just going through the docs as I learn about this project and would like to make modifications to increase the clarity.  I have a PR in the wings but wanted to file an issue first.

**To Reproduce**
n/a

**Expected behavior**
n/a

**Additional context**
Mostly these are just grammatical changes.  I've noted some opportunities to improve the clarity with some minor reworking of the structure, but nothing huge.  I also noted that there may be a bug in the pseudo code of the `RuleEngine_en.md` file that I've "fixed"  Basically, I think you need some extra `AND` elements in the conditions for the `< 1500` and `< 2000` rules because a fact where the price after tax is between `1000` and `1499.99` would match both and there's no priority associated with the rules.

**Comment by newm4n** [comment]
Hi @derekwyatt 
We greatly welcome and appreciate your contribution to this project. I am sure that the documentation have many-many flaws ugly structure, misspells, unclear explanations, etc. My self and some other contributors, although they are all wonderful developers, English for some of us, is not our mother tongue. 

Please don't hesitate to submit your PR.

**Comment by derekwyatt** [comment]
PR issued. Thanks for the implementation :D
