### ISSUE TITLE
Support utf-8 in structs, functions and similar just as go does

### ISSUE THREAD

**Issue by tpihl** [hyperjumptech/grule-rule-engine#169]
**Is your feature request related to a problem? Please describe.**
We have some strict language requirements within some of the public sector, where "business" expect to do their work in Swedish (with the crazy character å, ä and even ö).

It is fine to use those characters and other as variable names in go, but we generally avoid that since we define it as IT-specific woke.

However, a rule is something share by IT and busiess, where it really would make sense to be able to use non-ascii characters in structs and functions. Even better if we could translare the few keywords in a rule to Swedish as well (but that is minor). 

**Describe the solution you'd like**

Allow all runes in rules that are allowed in golang variable name.
(if easy, allow translation of the keywords in a rule as well).

**Describe alternatives you've considered**

* A preprocessor translating rules where we try to identify any non-ascii characters and figure out if it's inside a comment or is a real identifier will duplicate alot of the parsing already done by the rule engine.
* Just omit the dots give us a lot of trivial but annoying tries, since we use swedish words not spelled as we have learned to do

**Additional context**

**Comment by newm4n** [comment]
Hi @tpihl 

Thank your for pointing this to us. 
We immediately worked out a PR for this #170 and will release a patch for this ASAP.
I hope it covers most unicode's letters. 
If you finds any character not supported, please don't hesitate to make another ticket.

Cheers.

**Comment by newm4n** [comment]
New patch released for this...
https://github.com/hyperjumptech/grule-rule-engine/releases/tag/v1.8.3

**Comment by tpihl** [comment]
I can confirm it's working beautifully, thank you!!!!
