### ISSUE TITLE
Where can I get all the GRL keywords

### ISSUE THREAD

**Issue by easydo666** [hyperjumptech/grule-rule-engine#17]
hi，
i can not find GRL keywords。can you give some help？
thanks very much！

**Comment by newm4n** [comment]
I have a plan to write a document about GRL.
Hold tight.

**Comment by easydo666** [comment]
ok。I look forward to your better documentation。
i think grule is very good。

**Comment by newm4n** [comment]
List of functions has been documented.
The GRL syntax structure are there already explained.
