### ISSUE TITLE
fact support interface type

### ISSUE THREAD

**Issue by wangmingjunabc** [hyperjumptech/grule-rule-engine#174]
**Is your feature request related to a problem? Please describe.**
IOT area，when using rule engine to analysis the device data, the type of device value may not be determined in advance for different device may send different value。

**Describe the solution you'd like**
 when create fact for rule, can interface type be used?

**Comment by newm4n** [comment]
Hi @wangmingjunabc 

AFAIK, adding an `interface` into `Datacontext` will makes reference of `value` to an interface. Not a `value` to a `ptr`. This will render your fact's attribute or function not accessible by the engine. 

My advise is, to somehow convert your interface fact into `map[string][]interface` before adding to the `Datacontext`.

Or, have your device data tobe in `JSON` string, and add the `JSON` into data context using `AddJSON` function. This way, you can add arbitrary structure into the context.  [This example shows how to do it](https://github.com/hyperjumptech/grule-rule-engine/blob/90f4cf9e2ac03e8ceb1286ed85dc8fd47a45620e/examples/JSONDataContext_test.go).

**Comment by wangmingjunabc** [comment]
> Hi @wangmingjunabc
> 
> AFAIK, adding an `interface` into `Datacontext` will makes reference of `value` to an interface. Not a `value` to a `ptr`. This will render your fact's attribute or function not accessible by the engine.
> 
> My advise is, to somehow convert your interface fact into `map[string][]interface` before adding to the `Datacontext`.
> 
> Or, have your device data tobe in `JSON` string, and add the `JSON` into data context using `AddJSON` function. This way, you can add arbitrary structure into the context. [This example shows how to do it](https://github.com/hyperjumptech/grule-rule-engine/blob/90f4cf9e2ac03e8ceb1286ed85dc8fd47a45620e/examples/JSONDataContext_test.go).

Using map[string]interface and AddJSON function is a good idea. Another question is whether I can customize method for the map which like struct method used in then area of rules?

**Comment by newm4n** [comment]
@wangmingjunabc 

In theory Yes. Yet I have **not tested** it.

```
type MyMap map[string]string
func (m MyMap) MapMethod() {
   ...
}

...
amap := make(MyMap)
dataContext.Add("Map", amap)
...
```

and rule can do 

```
when
   true
then
   Map.MapMethod()
```

Any how, you can always have a work around by wrapping your map in a struct.
And add the struct as Fact into data context.
