### ISSUE TITLE
Allow use of new embed package for rule folder

### ISSUE THREAD

**Issue by tpihl** [hyperjumptech/grule-rule-engine#175]
**Is your feature request related to a problem? Please describe.**
It would be great to be able to embed the rules using the new embed package (in the cases when you want the rules static with the code

**Describe the solution you'd like**
Add a ResourceBundle or similar accepting a FS (as defined in embed examples.

**Describe alternatives you've considered**
We're currently embedding them in the container but it would be cleaner to embed them in the executable

**Comment by newm4n** [comment]
@tpihl 

We still maintain compatibility with those who uses Go 1.13, I have not see Go 1.16 in our plan yet.
Embed FS is part of 1.16

I will make this issue pinned until its time for us to move on.

**Comment by newm4n** [comment]
@tpihl 

There you go, in version v1.9.1.
Thanks a lot @niallnsec

**Comment by newm4n** [comment]
@tpihl 

When you've tried it and have nothing to add, please kindly close this issue.
