### ISSUE TITLE
grule does not support Operator Precedence ?

### ISSUE THREAD

**Issue by mountainswen** [hyperjumptech/grule-rule-engine#18]
1+2+3*4 = 24 in grule ?

**Comment by newm4n** [comment]
Hi Mountainswen, thanks for trying Grule and pointing this
Unfortunately, yes. Grule disregard Operator Precedence. I will keep this in mind for future improvement. 

However, Implementing Operator Precedence is some how not an easy task to implement, I need to re-structure the ANTLR4 grammar and adjust Rete algoritm for this. So this may take some time.

For now, user need to scope the expression into

```
1 + 2 + (3 * 4) = 15
```
 ...  to do it properly.

I will keep this issue alive until I implement it.

**Comment by newm4n** [comment]
There you go, operator presedence is now supported on release v1.2.0

```go
const OpPresedenceRule = `rule OpPresedenceRule "test operator presedence" salience 10 {
    when
        1 + 2 + 3 * 4 == 15
    then
        TestStruct.Result = 3;
		Retract("OpPresedenceRule");
}`

func TestEngine_OperatorPrecedence(t *testing.T) {

	ts := &TestStruct{}

	dctx := ast.NewDataContext()
	err := dctx.Add("TestStruct", ts)
	if err != nil {
		t.Fatal(err)
	}

	memory := ast.NewWorkingMemory()
	kb := ast.NewKnowledgeBase("Test", "0.0.1")
	rb := builder.NewRuleBuilder(kb, memory)
	err = rb.BuildRuleFromResource(pkg.NewBytesResource([]byte(OpPresedenceRule)))
	assert.NoError(t, err)

	engine := NewGruleEngine()
	err = engine.Execute(dctx, kb, memory)
	assert.NoError(t, err)

	assert.Equal(t, int64(3), ts.Result)
}
```

**Comment by mountainswen** [comment]
woo~ thx!
