### ISSUE TITLE
To save a KnowledgeLibrary into compiled "GRL" binary file and also to load them back.

### ISSUE THREAD

**Issue by newm4n** [hyperjumptech/grule-rule-engine#182]
**Is your feature request related to a problem? Please describe.**
Loading huge (thousands)  rule set takes time, some time it takes minutes. 

**Describe the solution you'd like**
Would be much helpful to be able to load huge rule set fast.

**Describe alternatives you've considered**
Have the KnowledgeLibrary to be able to be saved into a compact binary file and vice-versa.
This will remove the ANTLR4 parsing process and Expression/Atoms re-indexing RETE logic.
So loading from this binary and compact file is faster and straight forward into KnowledgeLibrary.

**Additional context**
All AST nodes is has its own ID and this could be very helpful to maintain AST node network.

**Comment by jinagamvasubabu** [comment]
hi @newm4n good to see this coming,  this would really help developers like me to use grules better even with big datasets


let me know if you need any help to pull this off

**Comment by newm4n** [comment]
Hi @jinagamvasubabu 

PR #183 is out. Thanks  a lot for your offer for help. 
I will release it ASAP, and when it done, you  could help me test it with big set of rule-sets. 
See if it load faster from binary file.

Another thought is, you could help me prepare documentation for that part. 
Storing KnowledgeBase to binary file and load it back. Or perhaps some documentation if people like to use archive/zip Reader/Writer to make the file size smaller.

Or, you could help to create such adapter. Or deployment pipeline where Rule developer could code GRL, and save it as compiled rule binary file. And deploy the binary file to server that exclusively read rule from binary file. This could open opportunity for more tooling in the Grule ecosystem.
