### ISSUE TITLE
how to validate rulea before running？

### ISSUE THREAD

**Issue by kennir** [hyperjumptech/grule-rule-engine#189]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by newm4n** [comment]
@kennir  , something wrong ?

**Comment by kennir** [comment]
@newmn I'm very sorry for the long time without feedback because l long trip ，There have some problem in practical use , We often get some rules wrong  likes a typo or missing a semicolon, Grule does not throw exceptions or warnings when encountering wrong rule script (Or maybe the error can be hidden by REST services),  Can we verify all the rules before loading them?
