### ISSUE TITLE
When the number of requests increases, the cost increases sharply

### ISSUE THREAD

**Issue by dyh1990** [hyperjumptech/grule-rule-engine#190]
We write a relatively large rule, which usually takes about 20 ms. But one day, the traffic suddenly doubled, and we found that the request all timed out。We added a new node, and everything became normal。

**environment**
linux, 2-core 4G

**pprof**
![image](https://user-images.githubusercontent.com/7194182/116809940-71934e00-ab73-11eb-81d8-181d4a9d6023.png)

**Comment by newm4n** [comment]
@dyh1990 

There are so many possibilities that can cause a performance drops. e.g.

- GRL calls user's custom functions that is not optimized for multithreading.
- Shared data context between engine execution can cause a kind of "racing" condition.
- KnowledgeLibrary.NewKnowledgeBaseInstance down to  engine.Execute which scoped in one mutex.

And so many other possibility. 
Its hard for us to know exactly if you don't share a reproducible code or snippets.
