### ISSUE TITLE
LHS reevaluate into Infinite loop when RHS Fact change

### ISSUE THREAD

**Issue by josephlim75** [hyperjumptech/grule-rule-engine#191]
**Clarification**
This is not a bug but clarification.  Does `grule` has the same mechanism like `no-loop` in `Drools` where when a RHS fact change causing the same LHS rule reevaluate and activate causing the rules to run in infinite loop.  Is this automatically implemented or we have to explicitly provide a DSL to tell it should not run into a loop

**Comment by newm4n** [comment]
Yes. To specify `GruleEngine.MaxCycle` you explicitly tell the engine, how many time an evaluation loop can happen. If it loops infinitely, you run into an error as [explained in the FAQ](https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/FAQ_en.md#1-grule-panicked-on-maximum-cycle)
