### ISSUE TITLE
Support $in operator

### ISSUE THREAD

**Issue by william8188** [hyperjumptech/grule-rule-engine#194]
**Is your feature request related to a problem? Please describe.**

Like SQL, I want to make a condition, like `where name in ("Jack", "Mike", "Ben") `.
But I find out there is no operators in grule like this `$in` operator.

**Describe the solution you'd like**

Please support `$in` operator.

**Comment by jinagamvasubabu** [comment]
Yes it would be a good addition, i actually solved this with `OR` condition. (Just a workaround :)) 

For In condition:
Eg: (Fact.Name == "Jack" || Fact.Name == "Mike" || Fact.Name == "Ben")

For Not in Condition:
Eg: (Fact.Name != "Jack" && Fact.Name != "Mike" && Fact.Name != "Ben")

**Comment by newm4n** [comment]
@william8188 

Just released 1.8.6.
`In` function is now available.
https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/Function_en.md#stringinstring--bool

**Comment by william8188** [comment]
> @william8188
> 
> Just released 1.9.0.
> `In` function is now available.
> https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/Function_en.md#stringinstring--bool

Thank you for your supporting. @newm4n
