### ISSUE TITLE
Getting build error while building the gure engine

### ISSUE THREAD

**Issue by nagarajtrivedi** [hyperjumptech/grule-rule-engine#228]
Hi all, I am Nagaraj Trivedi
I am facing an issue when tried executing make command
I am using the grule engine downloaded from the github. When tried building it I got the below error. Please let me know what could be the reason
~/go/grule-rule-engine$ make build
sed -i.origin.bak "s/1[ ]*<</int64(1) <</g" antlr/parser/grulev3/grulev3_parser.go
export GO111MODULE on;
go build ./...
go: cannot find GOROOT directory: /usr/local/opt/go/libexec
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 2

Please let me know what could be the reason

Thanks
Nagaraj

**Comment by newm4n** [comment]
Hi @nagarajtrivedi 

This should answer your question.. 
https://stackoverflow.com/questions/44954007/go-cannot-find-goroot-directory-usr-bin-go
