### ISSUE TITLE
In() bug

### ISSUE THREAD

**Issue by jeagle929** [hyperjumptech/grule-rule-engine#233]
**Describe the bug**
In() always false

**To Reproduce**
Rule as follows:
rule havesomeone “check whether have someone” salience 0 ｛
when
    user.Name.In(“one”,”two”,”three”)
then
    user.Print(“exists”);
}

when evaluate and execute that rule with user.Name=“one”, should see exists, but not,because of evaluating not pass.

**Expected behavior**
I hope when user.Name = “one”, evaluate rule will return true.

**Additional context**
type User struct {
Name string
Telephone string
}

**Comment by jeagle929** [comment]
As noted in the function comments: if no argument specified it will return false, 
but in code: len(arg) != 0 indicates the meaning of specifying argument.

**Comment by jinagamvasubabu** [comment]
yes code is not correct, will fix it

**Comment by newm4n** [comment]
@jeagle929 

Thanks a lot for pointing this out.

**Comment by newm4n** [comment]
It's fixed in the master. Will release patch soon.
