### ISSUE TITLE
Question: How to convert GRL to JSON bytes?

### ISSUE THREAD

**Issue by ndabAP** [hyperjumptech/grule-rule-engine#245]
I've a GRL file I'd like to convert to JSON. Is that possible? My approach:

```go
fileResource := pkg.NewFileResource("./rules.grl")
jsonResource := pkg.ParseJSONRuleset(fileResource)

b, _ := jsonResource.Load()
fmt.Println(string(b))
```

This results into an empty string.

**Comment by niallnsec** [comment]
Currently there is no function to take in a GRL syntax ruleset and output to JSON format. Internally, the JSON parsing works by processing the JSON rules into GRL format which is then passed to the engine, so conversion of GRL syntax to JSON was not implemented.

The function you are using above `pkg.ParseJSONRuleset` is meant to take in a ruleset already in JSON format and load it into the engine. The way you are currently using it will result in a parsing error from the `jsonResource.Load()` call.

**Comment by ndabAP** [comment]
Thank you very much for that detailed answer. We want to store GRL files inside our MongoDB database and find the syntax easier to read than JSON. Our solution will likely be to store GRL files as binary fields in MongoDB. Thanks again, I'll close it.

**Comment by mvberg** [comment]
Hi @niallnsec 

Thanks for the work on JSON -> GRL in #72!

> Currently there is no function to take in a GRL syntax ruleset and output to JSON format.  ..  so conversion of GRL syntax to JSON was not implemented.

Do you have any interest in tackling this feature (GRL -> JSON) for a proper bounty on on something like https://app.bountysource.com/?

@mayouzi also appeared to [show some interest](https://github.com/hyperjumptech/grule-rule-engine/pull/72#issuecomment-793462248) in the feature as well ...
