### ISSUE TITLE
How to export and import a single rule from the engine

### ISSUE THREAD

**Issue by mzs0207** [hyperjumptech/grule-rule-engine#247]
There is a web service that has too many rules to load all of them at startup. A knowledgeLibrary instance is created back for each request. Since loading rules from strings is slow, we want to cache the loaded rules. Now I have a problem, how to export and import a rule separately?

**Comment by newm4n** [comment]
Why would you rebuild the KnowledgeLibrary from .GRL script each time new request is coming ?
You only need to build the KnowledgeLibrary once the server is start, or if there's a rule change.

```
// When the app start
lib := ast.NewKnowledgeLibrary()
rb := builder.NewRuleBuilder(lib)
err := rb.BuildRuleFromResource("MyRuleSet", "0.0.1", pkg.NewBytesResource([]byte(MyRule)))
```

As you can see, your lib is a library of rules that you've loaded so far. It dont need reloading, and act as a cache of rules.
For each request, you only need to obtain a KnowledgeBase instance from the library ... 

```
// For each web service request
kb := lib.NewKnowledgeBaseInstance("MyRuleSet", "0.0.1")

dctx := ast.NewDataContext()
err = dctx.Add("ItemA", ia) // handle the error
err = dctx.Add("ItemB", ib) // handle the error
err = eng.Execute(dctx, kb) // handle the error
```

You can save your text GRL file into binary GRB file to make the rule loading 10 times faster, with the trade of rule file become 5 time larger. Heres how to do it... https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/Binary_Rule_File_en.md

**Comment by mzs0207** [comment]
> Why would you rebuild the KnowledgeLibrary from .GRL script each time new request is coming ? You only need to build the KnowledgeLibrary once the server is start, or if there's a rule change.
> 
> ```go
> // When the app start
> lib := ast.NewKnowledgeLibrary()
> rb := builder.NewRuleBuilder(lib)
> err := rb.BuildRuleFromResource("MyRuleSet", "0.0.1", pkg.NewBytesResource([]byte(MyRule)))
> ```
> 
> As you can see, your lib is a library of rules that you've loaded so far. It dont need reloading, and act as a cache of rules. For each request, you only need to obtain a KnowledgeBase instance from the library ...
> 
> ```go
> // For each web service request
> kb := lib.NewKnowledgeBaseInstance("MyRuleSet", "0.0.1")
> 
> dctx := ast.NewDataContext()
> err = dctx.Add("ItemA", ia) // handle the error
> err = dctx.Add("ItemB", ib) // handle the error
> err = eng.Execute(dctx, kb) // handle the error
> ```
> 
> You can save your text GRL file into binary GRB file to make the rule loading 10 times faster, with the trade of rule file become 5 time larger. Heres how to do it... https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/Binary_Rule_File_en.md

Thank you very much for your answer. Because there are about 800,000 rules, if all of them are imported, the memory consumption is very large and the execution is not efficient.

**Comment by jinagamvasubabu** [comment]
can you try this approach which is mentioned 
You can save your text GRL file into binary GRB file to make the rule loading 10 times faster, with the trade of rule file become 5 time larger. Heres how to do it... https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/Binary_Rule_File_en.md 

see how much time it is taking ?
