### ISSUE TITLE
Suggest that Execute start and finish logs be at debug level

### ISSUE THREAD

**Issue by chetananand** [hyperjumptech/grule-rule-engine#28]
These following logs are noisy and can be at debug level instead.

https://github.com/hyperjumptech/grule-rule-engine/blob/1a23c033b5d6696fbaa30aba42f4b4ac414ad7b8/engine/GruleEngine.go#L49

and 

https://github.com/hyperjumptech/grule-rule-engine/blob/1a23c033b5d6696fbaa30aba42f4b4ac414ad7b8/engine/GruleEngine.go#L140

**Comment by newm4n** [comment]
Hi Chetananand, 

Thanks for trying grule-rule-engine and pointing this out. I will review all Info level logs and lowered them to debug or trace.

You should expect them to be in on the next release.

**Comment by newm4n** [comment]
Its fix as of v1.2.1
