### ISSUE TITLE
Support regex match

### ISSUE THREAD

**Issue by gchen08** [hyperjumptech/grule-rule-engine#281]
**Is your feature request related to a problem? Please describe.**

It is quite often that we need to test whether a pattern matches a string in rule conditions, but grule currenty does not support such operator.

**Describe the solution you'd like**

Please support regex match operator.Thanks.

**Comment by jinagamvasubabu** [comment]
Sure, I am on it

**Comment by jinagamvasubabu** [comment]
Done - PR for the same https://github.com/hyperjumptech/grule-rule-engine/pull/284

**Comment by gchen08** [comment]
> Done - PR for the same #284

Great Job! Thx.
