### ISSUE TITLE
Engine execute function when errored should also return the rule name that panicked during rule execution

### ISSUE THREAD

**Issue by rajat002** [hyperjumptech/grule-rule-engine#317]
**Is your feature request related to a problem? Please describe.**
When a rule execution is panicked, it clearly logs the exact rule that panicked during execution

`ERRO[0760]/../github.com/hyperjumptech/grule-rule-engine@v1.10.6/engine/GruleEngine.go:176 github.com/hyperjumptech/grule-rule-engine/engine.(*GruleEngine).ExecuteWithContext() Failed execution rule : test_rule_1. Got error json field 'customer_id' is undefined  lib=grule-rule-engine package=engine`

However, the error returned from the engine.Execute() doesn't contain any information about the actual rule that was panicked.
`json field 'customer_id' is undefined`

It would be great if it also returns the rule name in the error string so that the client can parse it to figure out the exact rule that has some issue and possibly temporarily removes it from the Knowledge base to allow other rules to execute.

**Describe the solution you'd like**
The Simplest change that can be made at https://github.com/hyperjumptech/grule-rule-engine/blob/master/engine/GruleEngine.go#L177
```
// execute the top most prioritized rule
err := runner.Execute(dataCtx, knowledge.WorkingMemory)
if err != nil {
         log.Errorf("Failed execution rule : %s. Got error %v", runner.RuleName, err)
         //return err
         return fmt.Sprintf("%v, rule:%v", err, runner.RuleName)
}
```

**Describe alternatives you've considered**
Probably we can let the engine continue to execute further rules if one of the rules is panicked during execution. We have an option when creating a new Engine - ReturnErrOnFailedRuleEvaluation and that allows the engine to continue if one of the rules is panicked during evaluation. Maybe we can think of a similar option for execution say **ReturnErrOnFailedRuleExecution**?

**Additional context**
NA

**Comment by newm4n** [comment]
Hi @rajat002 

The thing is, failed execution will most likely will not change the underlying DataContext and thus will yield the same rule `when` scope to be evaluated `true` again and again, until the `MaxCycle` error appear. Thus it will not help.

However, your advise to return error with more information such as RuleSet.name in the error message seems helpful.

**Comment by rajat002** [comment]
Thanks, @newm4n for the update on this.
