### ISSUE TITLE
Unable to call interface function on an item in an array of interfaces

### ISSUE THREAD

**Issue by globalflea** [hyperjumptech/grule-rule-engine#334]
**Describe the bug**
Consider the interface definition

type IX interface{
  Get() int64
}

and an struct to contain an Array/Slice of X
type C struct {
   Items []*IX
}

if i pass an the struct C to the rule engine (as 'C') and there's a When clause that calls

  C.Items[0].Get() == 10

i get an error:  "got this node identified as "C.Items[0]" is not referencing an object thus function Get call is not supported"

I should not be getting an error, since the item in the array does implement the Get() method.  

if however, i pass in C with array of struct (instead of interface), it works.  

**To Reproduce**

**Expected behavior**
I would expect that the C.Items[0].Get() where C.Items[0] element is an interface with the Get() method  to succeed and return the right value

**Additional context**

**Comment by newm4n** [comment]
Fixen in PR #336 
Added examples/InterfaceDataContext_test.go
