### ISSUE TITLE
Improve CPU consumption

### ISSUE THREAD

**Issue by pasendra** [hyperjumptech/grule-rule-engine#339]
**Describe the bug**
Everytime a KnowledgeBase is cloned, the entry is cloned and a snapshot is created to compare the actual entry with the cloned one.

We've noticed in one of our apps, that the function GetSnapshot consumes a lot of CPU everytime is called. 

<img width="518" alt="image" src="https://user-images.githubusercontent.com/67378710/205094080-44597c7b-1ee7-4ccc-8389-e4a4edc8f8b0.png">

Is there any chance to skip the following code in `RuleEntry.go` in order to improve the cpu consumption?
```go
if e.GetSnapshot() != clone.GetSnapshot() {
```

**Comment by pasendra** [comment]
I don't mind to fork and create a Pull Request, but I would like to discuss what to do :)

**Comment by newm4n** [comment]
Hi @pasendra 

I can recall that this snapshot comparison between the original and cloned rule entry are for testing purpose. I realized that this should be inside a test, not here. And I've never witnessed the cloning process breaks the AST integrity in production. So I think its ok to move the comparison from RuleEntry.go to RuleEntry_test.go.

Thanks for pointing this out.

**Comment by stanley-xie** [comment]
Hi @newm4n 
When will the new Tag be released for this fix?
