### ISSUE TITLE
Support for Kind Interface and Pointer to Facts

### ISSUE THREAD

**Issue by rifqifatih** [hyperjumptech/grule-rule-engine#345]
I notice there is a similar Issue which was [closed](https://github.com/hyperjumptech/grule-rule-engine/issues/174). However, I think there is some use case which can still be consider supporting interface / pointer.

I'm currently providing the Facts through REST API which can be in any arbitrary form, hence `map[string]interface{}`. But rule evaluation gives me 
```
can not use data type of interface in EQ comparison
``` 
or
```
can not use data type of ptr in EQ comparison
```
if I use pointer.

**Solution**
I propose that in `reflectmath.go/Evaluate*` handles these "reference" type with e.g.:
```
func EvaluateEqual(left, right reflect.Value) (reflect.Value, error) {
	if left.Kind() == reflect.Pointer || left.Kind() == reflect.Interface {
		return EvaluateEqual(left.Elem(), right)
	}

	if right.Kind() == reflect.Pointer || right.Kind() == reflect.Interface {
		return EvaluateEqual(left, right.Elem())
	}
....
}
```
 
Would gladly make PR contribution but I would like to open this for discussion first to know what are the implications and if it's aligned with the design.

**Comment by newm4n** [comment]
Hi @rifqifatih 

I can not figure any implication at this point. Please submit your PR including a unit test that shows whether your fix really works. 
I will be very grateful if you can make a PR and make sure `make test` complete successfully.
