### ISSUE TITLE
Mutable Value issues

### ISSUE THREAD

**Issue by hieubui2409** [hyperjumptech/grule-rule-engine#364]
I have a fact with struct like below:
```
type MyFact struct {
	Data  []*OrderInfo
	First *OrderInfo
	Last  *OrderInfo

	MutableVar1 string
        MutableVar2 []string
        MutableVar3 []*EvaluationHistoryItem
}

type EvaluationHistoryItem struct {
	EvaluatedBy  string
	EvaluatedAt  int64
	ExchangeRate float64
}
```
When I try to change value (assign or append value to slice) `MutableVar1`/`MutableVar2`/`MutableVar3` by both builtin and custom functions, It didn't work.
But when I change my fact struct to (Put all fields need to be mutable inside another object):
```
type MyFact struct {
	Data  []*OrderInfo
	First *OrderInfo
	Last  *OrderInfo
	Evaluation *EvaluationInfo
}

type EvaluationInfo struct {
	MutableVar1 string
        MutableVar2 []string
        MutableVar3 []*EvaluationHistoryItem
}

type EvaluationHistoryItem struct {
	EvaluatedBy  string
	EvaluatedAt  int64
	ExchangeRate float64
}
```
I can update value of  `MutableVar1`/`MutableVar2`/`MutableVar3`  normally.
Tell me if I did anything wrong. Thank you.

**Comment by raymondsryang** [comment]
Meet the same problem

**Comment by yjagdale** [comment]
can you share rule, How you are trying to manipulate the values? Thanks.
