### ISSUE TITLE
Go 1.14 is not supported, make error!

### ISSUE THREAD

**Issue by ninyjun** [hyperjumptech/grule-rule-engine#49]
Go 1.14 is not supported, make error!

**Comment by newm4n** [comment]
Hi ninyjun,

Are you running the "make test" ?
If yes, I suspected that you have not installed golint.
You should run

```
go get -u golang.org/x/lint/golint
```

before running "make test".

I have tested compiling and test Grule using golang 1.14.

To prove this, I make a docker file contains 

```
FROM golang:1.14

WORKDIR /go/src/app
COPY . .

RUN go get -u golang.org/x/lint/golint
RUN make test
```

After that I call `docker build -t test-build .`

```
Sending build context to Docker daemon  2.457MB
Step 1/5 : FROM golang:1.14
 ---> 2421885b04da
Step 2/5 : WORKDIR /go/src/app
 ---> Using cache
 ---> 0e97c32f35a6
Step 3/5 : COPY . .
 ---> 11db23710ff1
Step 4/5 : RUN go get -u golang.org/x/lint/golint
...
...
...
Successfully built 3042af939be4
```

I dont see golang 1.14 build and test complains about compatibility issue.

**Comment by newm4n** [comment]
Since ninyjun have no further feedback and/or closed this issue. Lets close it.
