### ISSUE TITLE
Nested method calls

### ISSUE THREAD

**Issue by niallnsec** [hyperjumptech/grule-rule-engine#54]
**Is your feature request related to a problem? Please describe.**
When using helper functions I would like to be able to access data returned from the method call.

**Describe the solution you'd like**
I would like to be able to write a rule such as this:
```
rule NestedFunctionCall "Use a nested function call" : 10 {
    when
        Order.User().Name == "bob"
    then
        ....
}
```
where in Go
```Go
type OrderInfo struct {
    uid string
    Product string
    ...
}
type UserInfo struct {
    UserID string
    Name string
}

func (o *OrderInfo) User() (*UserInfo) {
     return someDB.GetUser(o.uid)
}
```
This is a trivial example but in more complex cases this is useful for accessing data when necessary that may be slow to access and in most cases is unnecessary.

**Describe alternatives you've considered**
I have considered using multiple helper functions to do this, nesting them as necessary but this results in a very clunky rule and obfuscates the meaning of the rule in my opinion.

**Additional context**
I have not got any prior experience using Antlr so I am not sure if this is possible but I imagine it should be.

**Comment by newm4n** [comment]
Hi Niallnsec,

This is a good feature to implement and I think it's doable.
Will modify the ANTLR grammar and play with it.

**Comment by niallnsec** [comment]
I was playing around with it a little bit, I didn't manage to get it to work completely though. The closest I got was getting the example above to work by defining:
```
nestedMethodCall
    : methodCall (DOT variable)+
    ;
```
and adding that to the list for expressionAtom. I also made a couple of changes in the Evaluate function for the ExpressionAtom so it could handle both the MethodCall and Variable being set. 

It all came apart however when I tried to extend it arbitrarily so you could have a rule like this:
```
rule NestedFunctionCall "Use a nested function call" : 10 {
    when
        Order.User().Group().Name == "Administrators"
    then
        ....
}
```
or like this:
```
rule NestedFunctionCall "Use a nested function call" : 10 {
    when
        Order.User().Username.Online().Status == "available"
    then
        ....
}
```
It would certainly nice to be able to chain method calls and variable access arbitrarily but I got stuck at that point.

If there is anything I can help with please do let me know!

**Comment by newm4n** [comment]
I would simply add the ExpressionAtom as follow

```
expressionAtom
    : constant
    | variable
    | functionCall
    | methodCall
    | expressionAtom DOT expressionAtom
    ;
```

This makes an expressionAtom to always nest-able with subsequent DOT
following a function call, method call, variable, (AND constant).

Case 1.

```
functionNameB().variableNameC
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Function call `functionNameB()` and ExpressionAtom contains Variable `variableNameC`

Case 2.

```
contextName.methodNameA().variableNameA
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `contextName.methodNameA()` and ExpressionAtom contains Variable `variableNameA`

Case 3.

```
contextName.methodNameB().functionNameA()
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `contextName.methodNameB()` and ExpressionAtom contains Function call  `functionNameA()`

Case 4.

```
contextName.methodNameC().variableNameB.methodNameD()
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `contextName.methodNameC()` and ExpressionAtom contains Method call  `variableNameB.methodNameD()`

Case 5.
Now it able to go further into more complex AST graph.

```
contextName.methodNameC().attributeB.methodNameD().attributeC.methodE()
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `contextName.methodNameC()` and ExpressionAtom contains another 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `attributeB.methodNameD()` and ExpressionAtom contains Method call  `attributeC.methodE()`

Case 6.
More deeper

```
contextName.methodNameC().attributeB.methodNameD().attributeC.methodE().attributeD
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `contextName.methodNameC()` and ExpressionAtom contains another 2 nested ExpressionAtom which are
ExpressionAtom contains Method call `attributeB.methodNameD()` and ExpressionAtom contains another 2 nested ExpressionAtom which are
ExpressionAtom contains Method call  `attributeC.methodE()` and ExpressionAtom contains Variable `attributeD`

Case 7.
It makes valid for constant to have function.

```
"some string".toUpper()
```

is an ExpressionAtom contains 2 nested ExpressionAtom which are
ExpressionAtom contains a constant `"some string"` and ExpressionAtom contains Function Call `toUpper`

or

```
"hello world".substr(0,5)
```

or

```
23.toString()
```

However, the function must be built in to the literals, And grule don't have this yet.
And one more thing, this could potentially open a new capability that makes Grule become not simple anymore. xP

**Comment by niallnsec** [comment]
That is a much more elegant and effective approach. 

I did try taking a similar approach whilst I was playing with the code earlier, but I kept on getting panics in places I was not expecting.

I hadn't thought about it but being able to call functions like this on constant values makes a lot of sense to me. Particularly for theoretical functions like substr(x,y) because I can see that being used like:
`Data.Value = "abcdefghijklmnopqrstuvwxyz".substr(Data.Start, Data.End)`
where Data would be an object being referenced in a rule.

It sounds like this could potentially open up a lot of relatively complex capabilities but still keeps the core rules of the engine simple and clear. Also I think it has a nice natural flow for someone writing rules to chain functions and variable access in this way. I am not sure what the complexities are from the code side though.

I did try something similar with the grammar but ended up getting panics in places I did not expect them. After a little while I came to the conclusion I need to get a better understanding on Antlr and the generated Go code to properly understand what is going on in places like GruleParserV2Listener.go (which is the first place I ran into problems).

While I am still learning more about Antlr, I could contribute some more builtin functions if that is helpful?

**Comment by liouxiao** [comment]
I think this feature (cascaded function call) is what I also want.

I have 2 structs, one nests another, and the sub-struct has a function. I'd like to invoke the sub-struct's function in Grule, but failed.

An example rule is:

```
rule CascadedFunctionCall "Check value in sub-struct" salience 10 {
    when 
		MF.ComplexAttribute.Match("abc")
    then
		...
}
```

where in Go

```
type MyFact struct {
	ComplexAttribute Entry
}

type Entry struct {
	Value string
}

func (entry *Entry) Match(v string) bool {
	return entry.Value == v
}
```

However, the evaluation will fail and return `got error while fetching function Match() parameter types. Got function Match not found`.

Currently there're 2 possible workarounds:

1. Add `&MF.ComplexAttribute` as another variable (e.g. `CA`) to DataContext, so I could change the rule as followings:

```
rule CascadedFunctionCall "Check value in sub-struct" salience 10 {
    when 
		CA.Match("abc")
    then
		...
}
```

or 

2. Use a helper like:

```
rule CascadedFunctionCall "Check value in sub-struct" salience 10 {
    when 
		Strings.Match(MF.ComplexAttribute.Value, "abc")
    then
		...
}
```

But I'd say both workarounds are not ideal.
