### ISSUE TITLE
Supporting concurrent threads executing rules

### ISSUE THREAD

**Issue by osangenis** [hyperjumptech/grule-rule-engine#60]
**Is your feature request related to a problem? Please describe.**
When using **grules** in a service, being able to serve concurrent requests with the same `KnowledgeBase` --  without having to parse source rules in each request -- would increase performance.

**Describe the solution you'd like**
Just having a method to clone a `KnowledgeBase` object would be enough. When having to serve a request, just clone the `KnowledgeBase` singleton instance and execute against a new `WorkingMemory`  and `DataCotext`. `GruleEngine` can be shared among threads with no issue right now.

**Describe alternatives you've considered**
- Splitting `KnowledgeBase` into `KnowledgeBase` and `WorkingKnowledgeBase` is another solution, where rules are only retracted on the later. `WorkingKnowledgeBase` is a clone of `KnowledgeBase` used only internally in `GruleEngine.Execute(...)`.

**Additional context**
Nothing else comes to my mind...

**Comment by newm4n** [comment]
Well, thanks a lot for pointing this out. 
The `KnowledgeBase` can not be used in multiple concurrent thread in its current condition.
I will work on this.

**Comment by newm4n** [comment]
This feature has been implemented on `v1.4.0`. Please check the `CHANGELOG.md` and `examples/Concurrency_test.go` to see how it works.

**Comment by osangenis** [comment]
Works like a charm @newm4n , awesome work!
