### ISSUE TITLE
Condition is not re-evaluated while the fact changed

### ISSUE THREAD

**Issue by irfanhanif** [hyperjumptech/grule-rule-engine#66]
I try to create two simple rules similar with the tutorial stated in the docs. These are my rules:

```
// Initial fact
// MF.IntAttr = 1200000

rule Rule1 "Desc of Rule1" salience 0 {
	when
		MF.IntAttr >= 100000
	then
		Log("Rule1 called");
		Retract("Rule1");
}

rule Rule2 "Desc of Rule2" salience -1 {
	when
		MF.IntAttr / 500000 > 0.0
	then
		Log("Rule2 called");
		MF.IntAttr = MF.IntAttr - 500000;
}
```

I expect the engine to re-evaluate the condition in the `Rule2` whenever a new cycle begins. And at some point, the condition will be false and the cycle done. But instead, I got an error like this:

```
panic: GruleEngine successfully selected rule candidate for execution after 5000 cycles, this could possibly caused by rule entry(s) that keep added into execution pool but when executed it does not change any data in context. Please evaluate your rule entries "When" and "Then" scope. You can adjust the maximum cycle using GruleEngine.MaxCycle variable.
```

It seems the engine is not re-evaluating the condition in `Rule2` and remember it as true causing the cycle to keep repeating again and again. Please advice if I am doing it wrong. Thanks.

**Comment by newm4n** [comment]
I need to test this. 
Please wait.

**Comment by jinagamvasubabu** [comment]
Even i am facing the same issue when i try to edit the rules

**Comment by jinagamvasubabu** [comment]
@irfanhanif - I think i got the issue, 

"Grule execute the same rule again and again because the WHEN condition keep yielding a valid result" - Picked from Faq page

Issue is once after the `Rule1` get executed it should not get picked up again by rule engine for that you need to add condition may be something like before, so that same rule wont get executed again. 
```
// Initial fact
// MF.IntAttr = 1200000

rule Rule1 "Desc of Rule1" salience 0 {
	when
		MF.IntAttr >= 100000 && MF.WhatToSay == ""
	then
		Log("Rule1 called");
                MF.WhatToSay = "Updated with Rule1";
}

rule Rule2 "Desc of Rule2" salience -1 {
	when
		MF.IntAttr / 500000 > 0.0
	then
		Log("Rule2 called");
		MF.IntAttr = MF.IntAttr - 500000;
}
```

basically we should add some condition so that `WHEN` clause wont get picked up again and again.

@newm4n  - Correct me if i am wrong

**Comment by xmlviking** [comment]
I would like to add I'm having the same issue.  
My fact's set has a number of attributes.  My rules evaluate them in context with another datacontext object. 

`rule PreferenceLocationWest "When cluster is located in the west, it's optimal" salience 1{
    when
        ClusterInstance.Location == "WEST" && ClientPreference.Location == "WEST"
    then
		ClusterInstance.LocationWeight = (ClusterInstance.LocationWeight + 25);
}`

ClientPreference is a non fact instance. Similar in the project examples to the CashFlow struct.   It's used as cross fact context.
ClusterInstance is a fact instance.   

I get the same error your seeing when trying this.   I'm not sure why this is occuring.   The only way to remove it is to do the ` Redact("PreferenceLocationWest");`  Any idea on the fix time frame on this?

**Comment by niallnsec** [comment]
Are you using the latest version of the engine? I tried to replicate your issue with the rules in the first comment but it worked as expected. I was not able to replicate your panic report. Here is the output when I ran the test using the rules and setting the context IntAttr field to 1200000:
```
[0] % go test -run TestTutorial
DEBU[0000] Added RuleEntry : Rule1                       lib=grule struct=GruleParserV2Listener
DEBU[0000] Added RuleEntry : Rule2                       lib=grule struct=GruleParserV2Listener
DEBU[0000] Loading rule resource : Byte array resources 279 bytes success. Time taken 2 ms 
DEBU[0000] Starting rule execution using knowledge 'Tutorial' version 0.0.1. Contains 2 rule entries  lib=grule struct=GruleEngineV2
DEBU[0000] Resetting Working memory                      lib=grule struct=GruleEngineV2
DEBU[0000] Initializing Context                          lib=grule struct=GruleEngineV2
DEBU[0000] Cycle #1                                      lib=grule struct=GruleEngineV2
DEBU[0000] Executing rule : Rule1. Salience 0            lib=grule struct=GruleEngineV2
INFO[0000] Rule1 called                                  lib=grule package=AST source=GRL
DEBU[0000] Executing rule : Rule2. Salience -1           lib=grule struct=GruleEngineV2
INFO[0000] Rule2 called                                  lib=grule package=AST source=GRL
DEBU[0000] Cycle #2                                      lib=grule struct=GruleEngineV2
DEBU[0000] Executing rule : Rule2. Salience -1           lib=grule struct=GruleEngineV2
INFO[0000] Rule2 called                                  lib=grule package=AST source=GRL
DEBU[0000] Cycle #3                                      lib=grule struct=GruleEngineV2
DEBU[0000] Executing rule : Rule2. Salience -1           lib=grule struct=GruleEngineV2
INFO[0000] Rule2 called                                  lib=grule package=AST source=GRL
DEBU[0000] Cycle #4                                      lib=grule struct=GruleEngineV2
DEBU[0000] Finished Rules execution. With knowledge base 'Tutorial' version 0.0.1. Total #4 cycles. Duration 0 ms.  lib=grule struct=GruleEngineV2
PASS
ok      github.com/hyperjumptech/grule-rule-engine/examples     0.166s

```

**Comment by niallnsec** [comment]
@xmlviking in your case, I am struggling to understand your example. In your rule:
```
rule PreferenceLocationWest "When cluster is located in the west, it's optimal" salience 1{ 
    when 
        ClusterInstance.Location == "WEST" && ClientPreference.Location == "WEST" 
    then 
        ClusterInstance.LocationWeight = (ClusterInstance.LocationWeight + 25); 
}
```
the then clause does not change any of the variables referenced by the when clause. So the engine will continue to evaluate the when as true since it hasn't changed.

**Comment by jinagamvasubabu** [comment]
@niallnsec - +1

**Comment by newm4n** [comment]
Maybe @xmlviking wants to add 25 into `ClusterInstance.LocationWeight` as long as the value of `ClusterInstance.Location` and `ClientPreference.Location` is "WEST", we need to see other rules that possibly changing those values to other than "WEST".

But what @niallnsec saying is the `when` validation must turned `false` if you want the rule to be ignored in the following cycles. Retracting the rule is to specifically instruct the engine to do just that, ignore the rule.
