### ISSUE TITLE
Any plan to support Complex Event Processing？

### ISSUE THREAD

**Issue by yupengfei** [hyperjumptech/grule-rule-engine#7]
This is a great tool, and will be better with cep support.

**Comment by newm4n** [comment]
Grule may indeed support CEP, it will treat incoming events as fact to be process as they arrived in real-time and make a "conclusion" out of it. However, further performance test and improvement might be needed before to confidently use it on a high load of event. 

Golang are known of its execution performance, thus it might be good idea to test Grule with some CEP case.

**Comment by newm4n** [comment]
This means that we need to implement a `fact` construct that dynamic and generic enough to store most event structure and easily call-able from within the DRL, lets call this a `generic-fact` or `gen-fact`. 

Thus, we need an adapter/translator model where developer can easily  translate their own `raw` event ( be it in Json or bytes) into this gen-fact. Once translated, the gen-fact is pushed into an async broker. 

Grule engine subscribe into this broker(eg. Kafka, RabitMQ, etc) and listen for incoming gen-fact on a specific topic.
Pulled gen-fact is then added into `DataContext` and executed in rule engine.

After rule engine execution, the resulted fact then should be put back into async broker  on a different topic. Let other system subscribe on to it and consume.
