### ISSUE TITLE
[Question/Feature Request] Do we have any benchmark tests available for Grule rule engine ? 

### ISSUE THREAD

**Issue by jinagamvasubabu** [hyperjumptech/grule-rule-engine#78]
Do we have any benchmarks available for Grule rule engine ?
* How fast it is with complex rules ?
* Exec time for Running Lots of rules etc ?

**Comment by newm4n** [comment]
None that I know of.

**Comment by jinagamvasubabu** [comment]
ok, will try to collate that info.

**Comment by jinagamvasubabu** [comment]
I have created a [PR](https://github.com/hyperjumptech/grule-rule-engine/pull/84) for the same, please give your valuable feedback

**Comment by jinagamvasubabu** [comment]
closing this issue
