### ISSUE TITLE
Is there any way i can pull all the rules matching a particular fact

### ISSUE THREAD

**Issue by jinagamvasubabu** [hyperjumptech/grule-rule-engine#80]
**Is your feature request related to a problem? Please describe.**
This is more like an enhancement

**Describe the solution you'd like**
I wanted to fetch all the rules matching a particular condition, this helps me to write logic to delete duplicate rules if there is a match in existing rules.

Eg: 
rule 1 when (A > 10 || B < 4)  then .....
rule2 when  (B < 5) then ....
rule 3 when (C > 4) then ....

Fact (input) is B < 6 then it should give me rule1 and rule2

**Comment by newm4n** [comment]
If multiple rules `when` scopes matches facts in data context, they are called `ConflictSet`, its a common concept in any RuleEngine. Its not to remove those in conflict, but implement a strategy on selecting which of the rule in conflict to execute (the Then part). You should understand [how rule engine works](https://github.com/hyperjumptech/grule-rule-engine/blob/master/docs/RuleEngine_en.md) with regard of ConflictSet.

**Comment by jinagamvasubabu** [comment]
Thanks @newm4n , Sorry my bad, didn't explain my requirement well, 
**_I correct my question this is not to delete the duplicate rules_**,  just to find out all the matching rules to show in the UI
Resolving conflict set can be done using `salience`.

let me give you some background

**Background:**:
I am storing all my rules in a Datastore and have written a small parser which converts every DB row into a `GRL`. So far good. Now i have a business requirement where i need to fetch all the rules which matches a fact/input (complete/incomplete fact). I have an UI to show matching rules in UI
Eg:
rule 1 when (A > 10 || B < 4) then .....
rule2 when (B < 5) then ....
rule 3 when (C > 4) then ....

Filter Condition:
B < 6 then it should give me rule1 and rule2



**Changes**:
I have done the changes in `GruleEngine.go` and created a method called `RulesMatch` 

Can i create a Pull request for this change ? let me know if you have any concerns.

**Comment by newm4n** [comment]
Yes of course, you can always create a PR (or Draft PR), let us see your code for us to understand your  Idea better.

**Comment by jinagamvasubabu** [comment]
https://github.com/hyperjumptech/grule-rule-engine/pull/81 @newm4n, I have created a PR for the same.
