### ISSUE TITLE
Working on quite major updates. Please hold your horse guys.

### ISSUE THREAD

**Issue by newm4n** [hyperjumptech/grule-rule-engine#98]
Im currently working on major changes in the Grule Rule Engine.
It involves changes in

1. ANTLR4 grammar changes which leads to ...
2. AST graph generation which leads to ...
3. Opportunity to enhance Golang value graph to be more predictable, testable yet simpler.

This updates will fix lots of issues, features and stability related issue.
Im aiming,

1. Introduce array and map traversal in rule.

```
rule X "X" {
   when 
       fact.someArray[23].stringVal == "abc" &&
       fact.someMap["56"].obj.IntValue > 100
   then
      fact.otherArray[12] = 23;
      fact.otherArray.append(45);
      fact.otherMap["abc"] = "def";
}
```

2. Function chaining and Constant's functions

```
    when
       person.GetFriendByName("lucas").IsFemale() &&
       person.GetAddress().Contains("Hill Rd") &&
       person.GetCoupon().StartWith("hill".toUpper())
   then
       ...
```

3. JSON fact support

```go
Fact := `{
     "s": "abc",
     "i": 123,
     "o": {
          "c", "xyz"
     } ,
     "a" [
          "abc", "def"
      ]
}`
```

Access the json dom from the rule.

```
    when
        Fact.s == "abc" && 
        Fact.o.c == "XYZ" &&
        Fact.a.len() > 0 && Fact.a[0] == Fact.s
    then
        Fact.a.append("ghi");
```

---

All these changes will have 100% compatibility with previous version, rule grammar and engine usage. You dont have to change your side of code. I try my best and  I hope ;p

---

So, if you guys found some bug or nice feature to add in the current version, please don't hesitate to post them here. I will incorporate them into this new builds. I am doing this in my spare time out side my regular working hour and try my best to have it done ASAP. So, while Im doing this, please be patient, your issue are looked after, so hold your horses.

**Comment by jinagamvasubabu** [comment]
@newm4n thanks a lot for working on these interesting features.

**Comment by newm4n** [comment]
I'm almost done. 
The  core feature is nearly complete, just need to do a little test here and there while its under review by hyperjumptech's internal team. PR #93 .
Feel free to view the changes in the PR or even clone/fork my development branch. 
newm4n:feat/slice-map-func

**Comment by newm4n** [comment]
Now its released. v1.6.0
