### ISSUE TITLE
Question: Find required facts for a goal

### ISSUE THREAD

**Issue by masenocturnal** [hyperjumptech/grule-rule-engine#99]
Hello, 
This is just a question which might be obvious to more experienced rules developers so apologies if this is basic. 

I have a few (contrived) rules:

1) if object.has("wheels") and object.has("engine") then object.classification = "car"
2) if object.classification == "car" and object.colour == "red" then car.make = "ferrari"
3) If car.make == "ferrari" and driver.age < 30 then insurance.risk = "high"

And I am trying to answer  the question "What is my risk rating" ?

Assuming I don't currently have any facts available, in order to answer my question, I need to ask the following questions (in order to populate the facts)

* does the object have wheels?
* does the object have an engine
* what is the object colour ?
* is the object a car ?
* what make is the car ?

If my goal is to answer the question "what is my risk rating" is there any way I can ask grule which facts are missing answers in order of which way i need to ask them ? 

Obviously happy to contribute if there isn't anything existing but I would like to get an understanding as to how I would go about doing this ?

**Comment by newm4n** [comment]
The rule engine have no way of knowing what facts are missing for a particular objective nor which rule to execute for your objective to complete. Its just a plain simple set of rules to validate against set of facts. If the fact is there (or not there) it will indicate some rule to execute. The rule action will tell us the result.

If you must know what fact to ask to the user using a rule, prior executing the actual rule for your actual goal, I would suggest you to prepare 2 set of rule. The first will validate completeness of your facts for any possible goal and the second will do the actual evaluation, only if the first set is satisfied.

**Comment by masenocturnal** [comment]
Thank you.
